version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    versioning-strategy: "increase-if-necessary"
    groups:
      development-dependencies:
        dependency-type: "development"
    commit-message:
      prefix: "build"
